### ISSUE TITLE
GLFW and Qt can't coexist in the IDE.

### ISSUE THREAD

**Issue by jdiez17** [DCPUTeam/DCPUToolchain#175]
We are having trouble making the emulator work properly within the IDE. The problem is that GLFW and Qt have their own event loops, and they interfere with each other. So the first time a glfw window is created, it (usually) works properly, but new windows after the first run ALWAYS fails.

We have several options:
- Figure out a way of "resetting" the state of the LEM1802 and SPED-3, so they don't have to create a window each time. This option is unsuitable, because the crash behaviour is quite random.
- Separate the LEM1802 and SPED3 "logic" from the "GUI" implementation with GLFW so we can have a GLFW and a Qt variant. This is painful because we'd have to figure out stuff like VSync again.
- Spawn the emulator on its own process and communicate with it using SDP. This is my preferred option, because although we'll have to make the socket server cross-platform, we can ensure that it will always run perfectly.

Anyway, it's going to be painful. @hach-que, could you please look into this?

**Comment by irik77587** [comment]
Finally after a lots of waiting we now have GLAD.

**Comment by hach-que** [comment]
This project is dead.
